// import type { Metadata } from "next";
'use client'

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";

import "./globals.css";
import Header from "@/component/Header";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const [queryClient] = useState(() => new QueryClient());
  return (
    <html lang="eng" className="bg-white " >
      <body>
      <QueryClientProvider client={queryClient} >
        <Header />
        {children}
        <div id="portal-root" />
      </QueryClientProvider>
      </body>
    </html>
  );
}
