export const DUMMY_PRODUCTS = [
    {id:'a1', image: '/assets/toothpaste.jpg', name: 'Toothpaste', price:'1500', slug:"Toothpaste", 
        description:"FreshMint Whitening Toothpaste is your daily solution for a brighter smile and fresher breath. Specially formulated with natural mint extracts and fluoride, it gently whitens your teeth while strengthening enamel and fighting plaque. With consistent use, it helps remove surface stains without harsh abrasives, leaving your mouth feeling clean and refreshed all day. This toothpaste offers a smooth, refreshing mint flavor that’s not too strong, making it ideal for both adults and teens. It’s free from artificial dyes and unnecessary chemicals, making it a safer, more natural choice for your oral care routine. Dentist-approved and cruelty-free, FreshMint is perfect for everyday use—just brush twice a day and enjoy the confidence of a clean, radiant smile."
    },
    {id:'a2', image: '/assets/soap1.jpg', name: 'Bathing Soap', price:'800', slug:"Bathing-Soap", description:
        "PureGlow Moisturizing Bathing Soap is a rich, creamy bar that gently cleanses while nourishing your skin with every wash. Formulated with skin-loving ingredients like shea butter and coconut oil, it leaves your body feeling soft, smooth, and refreshed — never dry or tight. Its mild lather effortlessly washes away dirt and impurities without stripping your skin of its natural moisture. Ideal for all skin types, this soap has a subtle, clean fragrance that lingers lightly on your skin, giving you a fresh and comfortable feel throughout the day. Whether used in the morning for an energizing cleanse or at night for a calming bath, PureGlow brings a gentle, hydrating touch to your daily routine."
    },
    {id:'a3', image: '/assets/hydrogen.jpg', name: 'Hydrogen', price:'2500', slug:"Hydrogen", description:
        "FreshCare 3% Hydrogen Peroxide Solution is a versatile antiseptic trusted for both oral hygiene and minor wound care. Used as a mild disinfectant, it helps prevent infection in cuts, scrapes, and burns by killing harmful bacteria on contact. When diluted, it can also be used as a mouth rinse to relieve minor mouth irritations and promote a cleaner, healthier smile. This solution is safe for external use and recommended by healthcare professionals for its effectiveness and gentle cleansing action. It’s ideal to keep in your home for first aid needs, oral rinsing, and even household cleaning tasks. With FreshCare Hydrogen Peroxide, you get a simple, effective solution for everyday health and hygiene."
    },
    {id:'a4', image: '/assets/bodyWash.jpg', name: 'Body wash', price:'4000', slug:"Body-Wash", description:
        "SilkSoothe Hydrating Body Wash is a luxurious, creamy cleanser that pampers your skin with every shower. Enriched with nourishing ingredients like aloe vera, glycerin, and vitamin E, it gently removes dirt and sweat while replenishing moisture, leaving your skin feeling soft, clean, and refreshed all day. The rich lather glides effortlessly over your skin and rinses off without residue, making it perfect for both morning routines and evening wind-downs. With its delicate, calming fragrance, SilkSoothe turns your daily shower into a soothing self-care ritual. Suitable for all skin types, it’s the gentle cleanse your skin will thank you for."
    },
    {id:'a5', image: '/assets/faceMask.jpg', name: 'Face Mask', price:'500', slug:"Face-Mask", description:
        "RadiantSkin Detox Clay Face Mask is a purifying treatment designed to draw out impurities, reduce excess oil, and leave your skin feeling smooth, refreshed, and visibly clearer. Made with natural kaolin clay and infused with soothing botanicals like green tea and aloe vera, this mask helps unclog pores, minimize breakouts, and improve skin texture without over-drying. Its creamy formula glides on easily and rinses off clean, making it perfect for weekly self-care routines or quick pick-me-ups when your skin feels dull or tired. Suitable for all skin types, especially oily and combination skin, RadiantSkin gives your complexion the gentle reset it deserves — so you can glow with confidence, naturally."
    },
    {id:'a6', image: '/assets/dentalFloss.jpg', name: 'Dental Floss', price:'1500', slug:"Dental-Floss", description:
        "FreshMint Glide Dental Floss is a smooth, shred-resistant floss designed to clean deeply between teeth and along the gum line. Its soft texture glides effortlessly, removing plaque and food debris from even the tightest spaces without causing irritation or discomfort. Perfect for daily use, this floss helps prevent cavities and gum disease by reaching areas your toothbrush can’t. With a refreshing mint flavor, it leaves your mouth feeling clean and your breath noticeably fresher after each use. Compact and easy to carry, it's great for use at home, at work, or while traveling. Add FreshMint Glide Dental Floss to your oral care routine for a cleaner, healthier smile you can feel confident about."
    },
    {id:'a7', image: '/assets/femWash.jpg', name: 'Feminine Wash', price:'1500', slug:"Feminine-Wash", description:
        "PureBloom Gentle Feminine Wash is specially formulated to support the natural pH balance of the intimate area while keeping you feeling clean, fresh, and confident throughout the day. Enriched with soothing natural ingredients like aloe vera and chamomile, it gently cleanses without irritation, dryness, or harsh chemicals. This feminine wash is free from dyes, parabens, and fragrances that can disrupt delicate skin. Its mild, plant-based formula makes it ideal for daily use, especially during menstruation, after workouts, or whenever you want to feel refreshed. Dermatologist-tested and gynecologist-approved, PureBloom is your go-to for safe, gentle, and effective feminine hygiene care."
    },
    {id:'a8', image: '/assets/bodyOil.jpg', name: 'Body Oil', price:'1500', slug:"Body-Oil", description:
        "GlowEssence Nourishing Body Oil is a lightweight, fast-absorbing formula crafted to hydrate, soften, and restore your skin’s natural glow. Infused with a blend of botanical oils like jojoba, almond, and vitamin E, it deeply moisturizes without leaving a greasy feel, leaving your skin silky-smooth and radiant all day long. Perfect for use after a shower or bath, this body oil locks in moisture while calming dry, dull, or sensitive skin. Its subtle natural fragrance adds a gentle, relaxing finish to your skincare routine. Whether you're pampering yourself at night or looking for a fresh, dewy look during the day, GlowEssence delivers rich nourishment and lasting softness for every skin type."
    },
];